BASE_TASK_CONFIG_PATH: habitat_extensions/config/vlnce_mla.yaml
TRAINER_NAME: dagger # dagger, or recollect_trainer
SIMULATOR_GPU_IDS: [0]
TORCH_GPU_ID: 0
NUM_ENVIRONMENTS: 4
TENSORBOARD_DIR: data/tensorboard_dirs/mla
CHECKPOINT_FOLDER: data/checkpoints/mla
EVAL_CKPT_PATH_DIR: data/checkpoints/mla
RESULTS_DIR: data/checkpoints/mla/evals_v13

EVAL:
  USE_CKPT_CONFIG: False
  SPLIT: val_unseen
  EPISODE_COUNT: -1

IL:
  epochs: 45
  batch_size: 5
  lr: 2.5e-4
  use_iw: True
  inflection_weight_coef: 3.2

  DAGGER:
    iterations: 1
    update_size: 10819
    p: 1.0
    preload_lmdb_features: False
    lmdb_features_dir: data/trajectories_dirs/mla_nrsub/trajectories.lmdb

MODEL:
  policy_name: MLAPolicy

  INSTRUCTION_ENCODER:
    bidirectional: True
  PROGRESS_MONITOR:
    use: True
    alpha: 1.0 # means theta in paper
  PEAK_ATTENTION:
    use: True
    type: 1 # can be 0,1,2,3, the order of ascending
    alpha: 0.4 # means lambda in paper
    sigma: 0.6
    steps: 97371
    threshold: 0.6
  MLA:
    feature_drop: 0.25 # means FD in paper
  CLIP:
    rgb_level: -2
  SEQ2SEQ:
    encoder_prev_action: True
    decoder_prev_action: True
